services:
  - type: web
    name: planit-backend
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py migrate
    startCommand: gunicorn backend.wsgi:application
    disk:
      name: data
      mountPath: /var/lib/data