"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os
from datetime import timedelta
from dotenv import load_dotenv

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-8pfan6!$)ev8+#mty^+fv5bw9ew=(820n@%g858j)!u0etc5qt'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False  # False in production

# Security settings for production
SECURE_SSL_REDIRECT = True
SECURE_HSTS_SECONDS = 31536000  # 1 year
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

ALLOWED_HOSTS = [
    'planit-backend-2f8w.onrender.com', 
    'localhost',
    '127.0.0.1'
]

# CORS Settings - Critical for frontend-backend communication
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "https://planit-frontend-b3z0k8h1e-anugrahs-projects-2159a6eb.vercel.app",
    "https://planit-frontend.vercel.app",
    "https://planit-frontend-hxbmyhcso-anugrahs-projects-2159a6eb.vercel.app"  # Added your new frontend URL
]

# Required for CSRF protection with CORS
CSRF_TRUSTED_ORIGINS = [
    'https://planit-backend-2f8w.onrender.com',
    'http://localhost:3000',
    'https://planit-frontend-b3z0k8h1e-anugrahs-projects-2159a6eb.vercel.app',
    'https://planit-frontend.vercel.app',
    'https://planit-frontend-hxbmyhcso-anugrahs-projects-2159a6eb.vercel.app'  # Added your new frontend URL
]

# These are NECESSARY for proper CORS functionality
CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

# These headers are required for JWT authentication and CSRF
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

# Essential for cookies/session to work cross-origin
CORS_ALLOW_CREDENTIALS = True

# Expose these headers to the frontend
CORS_EXPOSE_HEADERS = ['Content-Type', 'X-CSRFToken']

# Cookie settings - Critical for production with HTTPS
SESSION_COOKIE_SAMESITE = 'None'  # Required for cross-site cookies
CSRF_COOKIE_SAMESITE = 'None'     # Required for CSRF protection
SESSION_COOKIE_SECURE = True      # Only send over HTTPS
CSRF_COOKIE_SECURE = True         # Only send over HTTPS
SESSION_COOKIE_HTTPONLY = True    # Prevent client-side JS access
CSRF_COOKIE_HTTPONLY = False      # Allow JS to read CSRF token

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',  # Must be before any middleware that generates responses
    'users',
    'trips',
    'whitenoise.runserver_nostatic'
]

# Middleware order is CRUCIAL - CorsMiddleware must come first
MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # Absolutely must be first
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# DRF settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',  # More flexible than IsAuthenticated
    )
}

# JWT settings
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'ROTATE_REFRESH_TOKENS': True,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_COOKIE': 'access_token',  # Cookie name for JWT
    'AUTH_COOKIE_SECURE': True,     # HTTPS only
    'AUTH_COOKIE_SAMESITE': 'None', # Cross-site cookies
}

AUTH_USER_MODEL = 'users.User'

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'

# Database
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Disable APPEND_SLASH to avoid redirect issues with API endpoints
APPEND_SLASH = False